### ISSUE TITLE
Website's background image not extending to the bottom

### ISSUE THREAD

**Issue by nightknighto** [MLH-Fellowship/prep-project-22.AUG.PREP.2#53]
![image](https://user-images.githubusercontent.com/52013393/184556916-d97006e7-5913-46a9-99af-c109632ea12f.png)
The image should probably be fixed on the browser, i.e. it shouldn't move with scrolling.

**Comment by shengyuan-lu** [comment]
I think this issue is already resolved, so I will close this issue.

**Comment by linyanna** [comment]
The issue was still persisting for me and on the main page, so I've reopened it.
![Uploading Screen Shot 2022-08-17 at 4.22.20 PM.png…]()
